sudo: required

language: cpp

dist: trusty

group: edge

matrix:
  include:
    # VM-based 64-bit skylake build (GCC)
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      env:
      - DISTRIBUTION=ubuntu/trusty
      - DEPLOY_PACKAGE=true
      - DEPLOY_IMAGE=true
      - GENERIC_BUILD=false
      script:
      - bash ./CI/runci.sh ubuntu-14.04
      - sudo source ./CI/prepare-docker-image.sh
      - echo "Travis build dir: ${TRAVIS_BUILD_DIR}"
      - ls -lh ${TRAVIS_BUILD_DIR}
      - ls -lh ${TRAVIS_BUILD_DIR}/build
    # VM-based 64-bit generic build (GCC)
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      branches:
        only:
          - master
      env:
      - DISTRIBUTION=ubuntu/trusty
      - DEPLOY_PACKAGE=false
      - DEPLOY_IMAGE=true
      - GENERIC_BUILD=true
      script:
      - bash ./CI/runci.sh ubuntu-14.04
      - sudo source ./CI/prepare-docker-image.sh
      - echo "Travis build dir: ${TRAVIS_BUILD_DIR}"
      - ls -lh ${TRAVIS_BUILD_DIR}
      - ls -lh ${TRAVIS_BUILD_DIR}/build
    # VM-based 64-bit OSX build (Clang)
    #- os: osx
    #  osx_image: xcode9.2
    #  compiler: clang
    #  env:
    #  - DEPLOY_PACKAGE=false
    #  - DEPLOY_IMAGE=false
    #  - GENERIC_BUILD=false
    #  - UNIT_TEST=true
    #  - FUNC_TEST_BASE=true
    #  - FUNC_TEST_ADVANCED=false  # disable because OSX VM's are slow
    #  - FUNC_TEST_RECOVERY=false
    # Container based 64-bit Xenial build
    - os: linux
      dist: trusty
      sudo: required
      services:
      - docker
      env:
      - DISTRIBUTION=ubuntu/xenial
      - DEPLOY_PACKAGE=true
      - DEPLOY_IMAGE=false
      - GENERIC_BUILD=false
      before_install:
      - docker pull ubuntu:16.04
      script:
      - docker run --log-driver=none -a stdin -a stdout -a stderr --rm -ti -u root -e GENERIC_BUILD='false' -v "${TRAVIS_BUILD_DIR}":/opt/akumuli -w /opt/akumuli ubuntu:16.04 ./CI/runci.sh ubuntu-16.04
      - echo "Travis build dir: ${TRAVIS_BUILD_DIR}"
      - ls -lh ${TRAVIS_BUILD_DIR}
      - ls -lh ${TRAVIS_BUILD_DIR}/build

env:
  global:
  - secure: DHaTv1euwlpVgePMbw0LEBihzru8VP5RmY7/TUdEpS1dBlJx6nyT6lgmyRcdb19RmTBUXZl1hm7Zu8TfqJJgfty4o9EnpLfTHbY7JwglSqbOo7b/FNAa1Qi0RhVDwc/WvFJDYBUvOtPtVQbPtVtECXm8PZcRqfOuEjkbHmmnIk8=

# Ship Akumuli logs to the S3 bucket
addons:
  artifacts:
    provider: s3
    s3_region: us-west-2
    access_key_id: "$ARTIFACTS_KEY"
    secret_access_key: "$ARTIFACTS_SECRET"
    bucket: "$ARTIFACTS_BUCKET"
    acl: public_read
    paths:
    - "$HOME/akumuli.log"

# Packagecloud deployment configuration
deploy:
  provider: packagecloud
  repository: Akumuli
  username: Lazin
  dist: $DISTRIBUTION
  package_glob: "${TRAVIS_BUILD_DIR}/build/*.{deb,rpm}"
  token:
    secure: TNIqxlIMy4PUJIn65Yl7dyr1A+TVCMSCOUZOd/XlqlmjntFbxdBKY2M+bX5Cc+uOvNNxFU0m0/RpxYibeN8Juo3BTV0B8YJ4Hjr60F+Sag0UFvvDmxd4vzK+rm+XbYyyx0ukO2ETUxEqxaJaEi0CJPEvEiIeXyJAzIytoVNukkM=
  on:
    branch: build-matrix
    condition: $DEPLOY_PACKAGE = "true"
  skip_cleanup: true

after_success:
# Push docker image. Docker image should be created and the variables REPO,
# VERSION, and TAG should exist.
- if [[ $TRAVIS_PULL_REQUEST == "false" && $DEPLOY_IMAGE == "true" ]]; then
      docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
      docker push $REPO:$VERSION-$TAG;
  fi 
after_failure: 
- echo "Build failed"
